### ISSUE TITLE
Распознавание тегов IDv3

### ISSUE THREAD

**Issue by ZergsLaw** [audioid/audioid#3]
Возможно добавить вариативность, касательно первых 4 байтов, разрешая использовать IDv3?

**Comment by amavlyanov** [comment]
@ZergsLaw это противоречи стандарту `"fLaC", the FLAC stream marker in ASCII, meaning byte 0 of the stream is 0x66, followed by 0x4C 0x61 0x43`

https://xiph.org/flac/format.html

**Comment by powerman** [comment]
По сути, нужно даже не столько распознавание тегов ID3, сколько их пропуск и обычный анализ FLAC лежащего в этом файле после тегов ID3, сами теги можно по-прежнему брать из FLAC, наверное. Пример распознавания таких файлов утилитой `file`: `/path/to/file.flac: Audio file with ID3 version 2.4.0, contains:FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 10004820 samples`

**Comment by kirillDanshin** [comment]
я пытался придумать вариант реализации, который покрыл бы эти кейсы и не был кашей из костылей, но всё сходится к тому, что это особенности конкретного пула аудио. в данном случае лучшим вариантом будет всё-таки готовить аудио при загрузке и хранить данные уже по стандарту, без префикса ID3. я пока не разрабатываю какую-то более сложную эвристику по выбиванию тегов из файлов, которые могут даже быть без соответствующего маркера (я видел и `FlAc`, и `flac`, и `FLAC`, когда должен быть маркер `fLaC`, но эти файлы обычно ещё и содержат метаданные не по какому-либо стандарту). эту эвристику можно будет реализовать уже после релиза стримингового сервера, но её нужно и продумывать так, чтобы килотонна костылей для "ремонта" файлов не мешала производительности работы с валидными файлами, и при этом учитывала все возможные варианты некорректных медиафайлов.

говоря о том, что file умеет распознавать такие флаки: начало разработки актуальной версии file было в первой половине 1987 года, за эти годы file научился распознавать невероятное количество файлов, что не мешает ему по сей день выдавать в некоторых кейсах false positives. я мог бы делать seek к `fLaC`, но никакой гарантии того, что файл в действительности по итогу корректный, в таком случае нет, а дать псевдоправильный результат, как я считаю, сильно хуже, чем дать ошибку, которую можно обработать на стороне вызова.
